### PR TITLE
[WIP / DRAFT] Full landing page rewrite in SvelteKit 

### PR DESCRIPTION
**Pull request by BRGustavoRibeiro**
I'm trying to rewrite and create a better version of our landing page using SvelteKit. This is a WIP and I'm only starting to code it up.

Current status:
image

### CODE REVIEW

**Comment by MaddyUnderStars** [comment]
I'm not sure there's any point in rewriting our website at the moment, given we'll most likely be doing a full rebrand very soon.

**Comment by BRGustavoRibeiro** [comment]
@MaddyUnderStars I'm taking that under consideration - the new codebase will allow us to quickly change the name of the project (in all citations of the 'Fosscord' name) by using the i18n support. We just need to [change one string](https://github.com/fosscord/fosscord-landingpage/pull/72/files#diff-40b20bdc32cec125e07063505b9c1c8b21f6afa55bbed9b5d371a90baebd58d8) and everything should be fine 🙃

I'm not sure if the colors are going to be changed too, but it's possibly to quickly do it just changing the [theme main colors](https://github.com/fosscord/fosscord-landingpage/pull/72/files#diff-87a3f6dae97c9233706660e6eeb021decfec0b0030cae23a83cea814243ee611).

**Comment by MaddyUnderStars** [comment]
Cool. I'd recommend you create a design document first and send it to us so that we can provide suggestions or feedback etc, rather than putting a ton of work in and potentially not having it merged.

**Comment by BRGustavoRibeiro** [comment]
Don't worry - at this moment, I'm exploring Svelte and it's possibilities (I'm kinda learning it as I code this) - Even if it doesn't get merged in the end, the amount of things I will learn while I'm coding will make the journey worth it 🙃

_(And I'm honestly not that good with prototyping haha)_

**Comment by BRGustavoRibeiro** [comment]
I'm closing this one - I'm trying it again with a new UI framework and lots of new changes. I'll do a new PR when it turns into an MVP.

**Pull request closed without merging**
