### PR TITLE
Fosscord Landingpage V2

### PR DESCRIPTION
**Pull request by Flam3rboy**
### About
localhost_3000_about_

### CODE REVIEW

**Comment by Flam3rboy** [comment]
### Todo:
- [ ] dark mode
- [ ] Fosscord feature sections with description

**Review by xNaCly — APPROVED** [review]

**Comment by xNaCly** [comment]
> ### Todo:
> 
>     * [ ]  dark mode


why does our landingpage need a Darkmode?

**Review by xNaCly — APPROVED** [review]
works.
image

**Comment by Flam3rboy** [comment]
## Dark Mode
localhost_3000_
localhost_3000_about_

**Review by Stylix58 — APPROVED** [review]
This is beautiful! But for what reason you use now Vue with Nuxt (the client is using React bruh)?

**Comment by Flam3rboy** [comment]
yes @Intevel wanted to use it

**Comment by Stylix58** [comment]
Bruh bruh bruh!

**Comment by Stylix58** [comment]
You can merge it now?

**Pull request merged**
