### PR TITLE
Big improvements

### PR DESCRIPTION
**Pull request by Stylix58**
image

image

### CODE REVIEW

**Comment by Flam3rboy** [comment]
I don't like the first background, rather choose a clean simple fluid-like background

**Comment by xNaCly** [comment]
I personally enjoy the changes, are you certain, the changes are supported by all browsers? 

Firefox has a known history of not supporting transparency.

**Comment by Stylix58** [comment]
image

It works

**Comment by Stylix58** [comment]
image

**Comment by Stylix58** [comment]
You can merge, now?

**Comment by xNaCly** [comment]
> You can merge, now?

No because @Flam3rboy still has requested changes.

**Comment by Stylix58** [comment]
> I don't like the first background, rather choose a clean simple fluid-like background

The background need so to be dark?

**Comment by Flam3rboy** [comment]
No a simpler cleaner version of something like this

**Comment by Stylix58** [comment]
image

**Comment by Flam3rboy** [comment]
No not flames xD
Make a simple fluid background similar like the example I sent earlier

**Comment by Stylix58** [comment]
ok

**Comment by Stylix58** [comment]
https://paveldogreat.github.io/WebGL-Fluid-Simulation/

**Comment by Stylix58** [comment]
I don't have another generator than this.
Do you know a other generator?
(xD I don't say how to do myself)

**Comment by Flam3rboy** [comment]
we need someone who designs one in e.g. photoshop

**Comment by Stylix58** [comment]
Ok, but I think we should merge now and make an another PR for this.

**Comment by Stylix58** [comment]
Ok, but I think we should merge now and make an another PR for this.

**Review by xNaCly — CHANGES_REQUESTED** [review]
Will be merged after background is changed according to @Flam3rboy's requests

**Review by Stylix58 — COMMENTED** [review]
I have added the waves!

image

**Comment by Flam3rboy** [comment]
Can you use the waves from https://github.com/jhcpeixoto/fosscord-landingpage

**Comment by Stylix58** [comment]
I use these waves!

**Comment by Stylix58** [comment]
image
Reverted the waves

**Comment by Flam3rboy** [comment]
No still wrong you should use the waves from  https://github.com/jhcpeixoto/fosscord-landingpage

**Comment by Stylix58** [comment]
I use the waves from this guy already! You see?

**Comment by Flam3rboy** [comment]
no these are the ones you should use
image

but you did this:
image

**Comment by Stylix58** [comment]
ok, i see

**Comment by Stylix58** [comment]
@jhcpeixoto what css you use for change colors of the waves?

**Comment by Stylix58** [comment]
Anyboy can build and share an screenshot of the landing page with the new commits pls?

**Comment by jhcpeixoto** [comment]
> Anyboy can build and share an screenshot of the landing page with the new commits pls?
> (I can't now because I can't use an computer now)

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#4081fc",endColorstr="#8d44fe",GradientType=1);

**Comment by Stylix58** [comment]
thanks!

**Comment by Stylix58** [comment]
When I try to add the gradient, its don't show! @jhcpeixoto

**Comment by Stylix58** [comment]
@Flam3rboy You can check this PR?

**Comment by Flam3rboy** [comment]
Can you show a screenshot of your current version

**Comment by Stylix58** [comment]
> Can you show a screenshot of your current version

I can't for now. So, try to clone the repo and do the commands listed in readme or wait one week.

**Comment by Flam3rboy** [comment]
image
these waves look great

**Comment by Stylix58** [comment]
Ok.
@jhcpeixoto , you can help me with this? (send me a dm on discord for answer) (i am on my pc in 2 days!)

**Comment by Flam3rboy** [comment]
https://www.shapedivider.app/

**Pull request closed without merging**
